CREATE TABLE EMPRESA (
    ID INTEGER NOT NULL,
    NOME VARCHAR(120) NOT NULL,
    CNPJ VARCHAR(32),
    ATIVO CHAR(1) DEFAULT 'S',
    CONSTRAINT PK_EMPRESA PRIMARY KEY (ID)
);

CREATE TABLE FORNECEDOR (
    ID INTEGER NOT NULL,
    NOME VARCHAR(120) NOT NULL,
    DOCUMENTO VARCHAR(32),
    EMAIL VARCHAR(120),
    ATIVO CHAR(1) DEFAULT 'S',
    CONSTRAINT PK_FORNECEDOR PRIMARY KEY (ID)
);

CREATE TABLE CATEGORIA (
    ID INTEGER NOT NULL,
    NOME VARCHAR(120) NOT NULL,
    TIPO VARCHAR(32) DEFAULT 'expense',
    ATIVO CHAR(1) DEFAULT 'S',
    CONSTRAINT PK_CATEGORIA PRIMARY KEY (ID)
);

CREATE TABLE CONTA_BANCARIA (
    ID INTEGER NOT NULL,
    NOME VARCHAR(120) NOT NULL,
    BANCO VARCHAR(60),
    AGENCIA VARCHAR(20),
    CONTA VARCHAR(40),
    ATIVO CHAR(1) DEFAULT 'S',
    CONSTRAINT PK_CONTA_BANCARIA PRIMARY KEY (ID)
);

CREATE TABLE TITULO_PAGAR (
    ID INTEGER NOT NULL,
    FORNECEDOR_ID INTEGER,
    CATEGORIA_ID INTEGER,
    CONTA_ID INTEGER,
    DESCRICAO VARCHAR(160),
    VALOR NUMERIC(15, 2) NOT NULL,
    VENCIMENTO DATE NOT NULL,
    STATUS VARCHAR(32) DEFAULT 'pending',
    CONSTRAINT PK_TITULO_PAGAR PRIMARY KEY (ID),
    CONSTRAINT FK_TITULO_FORNECEDOR FOREIGN KEY (FORNECEDOR_ID) REFERENCES FORNECEDOR (ID),
    CONSTRAINT FK_TITULO_CATEGORIA FOREIGN KEY (CATEGORIA_ID) REFERENCES CATEGORIA (ID),
    CONSTRAINT FK_TITULO_CONTA FOREIGN KEY (CONTA_ID) REFERENCES CONTA_BANCARIA (ID)
);

CREATE TABLE DESPESA (
    ID INTEGER NOT NULL,
    CATEGORIA_ID INTEGER,
    DESCRICAO VARCHAR(160),
    VALOR NUMERIC(15, 2) NOT NULL,
    DATA_DESPESA DATE NOT NULL,
    CONSTRAINT PK_DESPESA PRIMARY KEY (ID),
    CONSTRAINT FK_DESPESA_CATEGORIA FOREIGN KEY (CATEGORIA_ID) REFERENCES CATEGORIA (ID)
);

CREATE TABLE USUARIO (
    ID INTEGER NOT NULL,
    NOME VARCHAR(120) NOT NULL,
    EMAIL VARCHAR(120) NOT NULL,
    ATIVO CHAR(1) DEFAULT 'S',
    PAPEIS VARCHAR(160),
    CONSTRAINT PK_USUARIO PRIMARY KEY (ID)
);

COMMIT;
